config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations',
                                    omniauth_callbacks: 'callbacks' }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
  end

  devise_scope :user do
    get 'signup', to: 'devise/registrations#new'
  end

  resources :posts do
    resources :comments
  end

  resources :memberships, only: [:index, :new, :create, :show]

  resources :groups, only: [:show]

  root 'pages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :memberships
  has_many :users, through: :memberships
end

app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :user
  belongs_to :group
  has_many :posts
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :membership
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
   :omniauthable, :omniauth_providers => [:facebook]

  has_many :memberships
  has_many :comments
  has_many :groups, through: :memberships

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
      user.password = Devise.friendly_token[0,20]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  helper :all

  def current_membership
    Membership.find_by_user_id_and_group_id(current_user.id, Group.all.find(session[:current_group_id]))
  end
end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env['omniauth.auth'])
    sign_in_and_redirect @user
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @comments = Comments.all
  end

  def create
    @post = Post.find(params[:post_id])
    @comment =
    @post.comments.create(params[:comment].permit(:comment))
    @comment.user_id = current_user.id if current_user
    @comment.save

    if @comment.save
      redirect_to post_path(@post)
    else
      render 'new'
    end
  end

  def edit
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
  end

  def update
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])

    if @comment.update(params[:comment].permit(:comment))
      redirect_to post_path(@post)
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  helper :all

  def show
    set_group
    redirect_to '/'
  end

  private

  def set_group
    if params[:current_group]
      @group = Group.all.find(params[:current_group])
      session[:current_group_id] = @group.id
    end
  end
end

app/controllers/memberships_controller.rb
# frozen_string_literal: true

class MembershipsController < ApplicationController
  before_action :index

  def index
    @memberships = Membership.all
  end

  def new
    @membership = current_user.memberships.build
  end

  def create
    @membership = current_user.memberships.build(membership_params)
    check_record
  end

  private

  def check_record
    if current_user.memberships.exists?(@membership.group_id)
      render 'new'
      flash[:notice] = "You've already joined that group"
    else
      @membership.save
      redirect_to @membership
    end
  end

  def membership_params
    params.require(:membership).permit(:permission, :user_id, :group_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @posts = Post.all.order("created_at DESC")
  end

  def new
    @post = current_membership.posts.build
  end

  def create
    @post = current_membership.posts.build(post_params)

    if @post.save
      redirect_to @post, notice: 'The post was created!'
    else
      render 'new'
    end
  end

  def show; end

  def edit; end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: "You've updated your post!"
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path, notice: 'Your post was deleted'
  end

  private

  def find_post
    @post = Post.find(params[:id])
  end


  def post_params
    params.require(:post).permit(:title, :content, :membership_id)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:username, :email, :password, :password_cofirmation, :first_name, :last_name)
  end

  def account_update_params
    params.require(:user).permit(:username, :email, :password, :password_cofirmation, :first_name, :last_name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
  # sets current_users membership groups
  def user_group_ids
    @group_ids = []
    Membership.all.each do |membership|
      if membership.user_id == current_user.id
        @group_ids << membership.group_id
      end
    end
    @group_ids
  end

  # destroys numerical rep of user groups & returns an array user group records
  def current_user_groups
    user_group_ids
    @group_ids.collect do |id|
      Group.all.find_by_id(id)
    end
  end

  def current_group_name
    if session[:current_group_id].nil?
      @current_group ||= ''
    else
      @current_group = Group.all.find(session[:current_group_id]).name
    end
  end

  def check_group?
    !session[:current_group_id].nil?
  end
end

app/helpers/memberships_helper.rb
module MembershipsHelper
  # checks if current_user is a member of any group
  def check_membership?
    current_user.memberships.exists?
  end

  # checks if user has any post
  # def membership_posts?
  #  return unless check_membership?

  #  memberships = Membership.find_by_user_id(current_user.id)
  #  memberships.posts.exists?
  # end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div id="comments">
  <div class="comment">
    <p class="comment_content"><%= comment.comment %>
      <div class="buttons">
        <%= link_to "Edit", edit_post_comment_path(comment.post, comment) %>
        <%= button_to "Delete", [comment.post, comment], method: :delete, data: { confirm: "Are you sure you want to do this? "} %>
      </div>
    <p class="comment_author"><%= "- #{comment.user.first_name}" + " " + "#{comment.user.last_name.slice(0)}." %></p>
  </div>
</div>

app/views/comments/_form.html.erb
<%= form_for ([@post, @post.comments.build]) do |f| %>
  <%= f.text_area :comment %><br/>
  <%= f.submit %>
<% end %>

app/views/comments/edit.html.erb
<div id="comments">
  <div class="wrapper">
  <h2 style="color: white;">EDIT REPLY</h2>

  <%= form_for([@post, @comment]) do |f| %>
    <%= f.text_area :comment %>
    <p style="float: right;"><%= f.submit %></p>
  <% end %>
  </div>
</div>

app/views/layouts/_nav.html.erb
<link rel= "stylesheet", href="https://fonts.googleapis.com/css?family=Lato", type="text/css" />

<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <%= render 'layouts/nav/header'%>

    <%= render 'layouts/nav/links' %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Thrive</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <br>
    <br>
    <center><%= notice %><center>
    <center><%= alert %><center>
    <br>
    <br>
    <%= yield %>
  </body>
</html>

app/views/layouts/nav/_header.html.erb
<div class="navbar-header">
  <ul>
    <li><%= link_to 'T.F.I.O. Inc. - FORUM', root_path, class: 'nav-brand' %></li>
    <% if signed_in? %>
      <li style="color: white;"><center><%= current_group_name %><center></li>
    <% end %>
  </ul>
</div>

app/views/layouts/nav/_links.html.erb
<div class="nav-links navbar-right">
  <ul class="nav navbar-nav">
    <% if user_signed_in? %>
      <li><%= link_to 'Join Group', new_membership_path %></li>
      <% if check_membership? && check_group? %>
        <li><%= link_to 'New Post', new_post_path %></li>
      <% end %>
      <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
      <li><%= link_to 'Log Out', destroy_user_session_path, :method => :delete %></li>
    <% else #user signed out %>
      <li><%= link_to 'Login', login_path %></li>
      <li><%= link_to 'Signup', signup_path %></li>
    <% end #if user is signed in %>
  </ul>
</div>

app/views/memberships/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-5 col-sm-offset-4">
      <h2 class="text-center">Join a Group</h2>
        <%= bootstrap_form_for @membership do |f| %>

            <%= f.hidden_field :user_id, value: current_user.id %>

            <%= f.hidden_field :permission, value: 'student' %>

            <% options = options_from_collection_for_select(Group.all, 'id', 'name')%>
            <%= f.select  :group_id, options %>

           <%= f.submit "Join", class: 'form-control' %>
        <% end %>
    </div>

  </div>

app/views/memberships/_membership_post.html.erb
<div id="posts">
  <div class="wrapper">
    <h2>T.F.I.O INC. - THRIVE FORUM</h2>
      <% @posts.each do |post| %>
      <div class="post">
        <h2 class="title"><%= link_to post.title, post %></h2>
        <p class="date">Published <%= time_ago_in_words(post.created_at) %> ago
        </p>
      </div>
      <% end %>
    </div>
</div>

app/views/memberships/new.html.erb
<%= render 'form'  %>

app/views/memberships/show.html.erb
<h1>You've successfully joined!</h1>
<br />
<br />
<h4><%= link_to "back to homepage", root_path %></h4>

app/views/pages/_groups.html.erb
<% if signed_in? %>
  <h1>YOUR GROUPS</h1>
  <% if check_membership? %>
    <% current_user_groups.each do |group| %>
    <ul>
      <li><%= link_to group.name, group_path(group, :current_group => group) %></li>
    </ul>
    <% end %>
  <% else %>
    <h1><%= link_to 'Join A Group', new_membership_path %></h1>
  <% end %>
<% end %>

app/views/pages/_user_post.html.erb
<% if signed_in? %>
<div id="col-sm-3 single-post-card">
  <div class="card">
<!--  <%# if membership_posts? %> -->
        <% Membership.all.each do |membership| %>
            <% @group_name = Group.find_by_id(membership.group_id).name %>
          <% membership.posts.each do |post| %>
            <% if current_user.memberships.find_by_id(post.membership_id) %>
          <div class="post-text">
          </div>
          <div class="post-content">
            <h2><%= link_to post.title, post %></h2>
            <h5><%= @group_name %></h5>
            <p><%= post.content %></p>
            <div class="posted-by">
              <p class="date">Published <%= time_ago_in_words(post.created_at) %> ago
              <%= "by - #{current_user.first_name}" + " " + "#{current_user.last_name.slice(0)}." %>
            </div>
          </div>
          <% end %> <!-- if current user -->
        <% end %> <!-- membership.posts iteration -->
      <% end %> <!-- memership.all iteration -->
    </div>
  </div>
  <!-- <%# end %> -->
<% end %>

app/views/pages/index.html.erb
<div class="container">
  <div class="row">
    <div id="side-menu"  class="col-sm-3">
     <%= render 'groups' %>
    </div><!-- side-menu -->
    <div id="main-content" class="col-sm-9">
     <%= render 'user_post' %>

    </div><!-- main-content -->

  </div><!-- row -->
</div><!-- container -->

app/views/posts/_new_post.html.erb
<div class="new_post">
  <div class="col-sm-8 col-sm-offset-2">
  <%= bootstrap_form_for @post do |f| %>
    <%= f.text_field :title %><br/>
    <%= f.text_area :content %><br/>
    <%= f.submit %>
  <% end %>
  </div>
</div>

app/views/posts/edit.html.erb
<div id="posts">
  <div class="wrapper">
  <h2 style="color: #CC0000; ">EDIT POST</h2>

  <%= render 'new_post' %>

  <%= link_to "Cancel", post_path %>
  </div>
</div>

app/views/posts/index.html.erb
<div id="posts">
  <div class="wrapper">
    <h2>T.F.I.O INC. - THRIVE FORUM</h2>
      <% @posts.each do |post| %>
      <div class="post">
        <h2 class="title"><%= link_to post.title, post %></h2>
        <p class="date">Published <%= time_ago_in_words(post.created_at) %> ago
        <%= "by - #{post.user.first_name}" + " " + "#{post.user.last_name.slice(0)}." %>
        </p>
      </div>
      <% end %>
    </div>
</div>

app/views/posts/new.html.erb
<div id="">
  <div class="">
  <h2 style="color: #CC0000; ">NEW POST PAGE</h2>

  <%= render 'new_post' %>
  </div>
</div>

app/views/posts/show.html.erb
<div id="post_content">
  <h1><%= @post.title %></h1>
  <p><%= @post.content %></p>
<br/>
<hr/>
<br/>
<div id="comments">
  <h2><%= @post.comments.count %> Comments </h2>
  <%= render @post.comments %>
<br/>
  <h3>Reply to thread</h3>
  <%= render "comments/form" %>
</div>
  <div id="new_post">
    <div class="button">
      <%= link_to "Edit", edit_post_path(@post) %><a/>
      <%= button_to "Delete", post_path(@post), method: :delete, data: { confirm: "Are you sure you want to do this? "} %>
      <%= link_to "Home", root_path %>
    </div>
  </div>
</div>